### ISSUE TITLE
port to use as a standalone react library?

### ISSUE THREAD

**Issue by argosang** [PaulShestakov/aws-step-functions-constructor#14]
I'd like to embed this in a react application... how difficult or feasible is this?  I've never built a VS Code extension before.

**Comment by paulshestakov** [comment]
Just a summary, what's this extension doing:
- Parse a file(json or jml)
- Build a graph in graphlib library format from step function ([happening in here](https://github.com/PaulShestakov/aws-step-functions-constructor/blob/aec69f4b7f34313861075f9c3e944b509bcc0f3c/src/buildGraph.ts))
- Serialize it, send it via postMessage API to client app and render there using DagreD3 renderer ([happening here](https://github.com/PaulShestakov/aws-step-functions-constructor/blob/aec69f4b7f34313861075f9c3e944b509bcc0f3c/media/main.js))

Maybe you can just take this (step function into graphlib graph [transform](https://github.com/PaulShestakov/aws-step-functions-constructor/blob/aec69f4b7f34313861075f9c3e944b509bcc0f3c/src/buildGraph.ts#L11)) and then render using DagreD3 [here](https://github.com/PaulShestakov/aws-step-functions-constructor/blob/aec69f4b7f34313861075f9c3e944b509bcc0f3c/media/main.js#L42)
