### ISSUE TITLE
Map steps not visually correct

### ISSUE THREAD

**Issue by lj9142** [PaulShestakov/aws-step-functions-constructor#16]
This looks really useful and look forward to using it but an issue we have is that we use a map step function but it shows it as one box but i would have expected it to look a bit like the parallel where it is an outline and the lambda steps we have inside it are boxes within it to make it clear what is happening inside it. 

Is this expected behaviour at the moment? Is there any plans to change the visual for this?

Thanks!

**Comment by paulshestakov** [comment]
Map step was indeed missing in visual 😞
Thanks, I've just pushed the change. If you you update your extension it will look like this
![image](https://user-images.githubusercontent.com/9156851/104103618-25668a00-52b4-11eb-9176-34be9c5a3e15.png)

**Comment by lj9142** [comment]
Brilliant, that is working for me now, thanks for the speedy fix! 

I have one more, for steps in the case of an error, there is no link to the step they come from as you can see here:

![image](https://user-images.githubusercontent.com/22213596/104177633-00cbf880-5401-11eb-9dc6-227f29153c5e.png)

Is it possible to get that fixed? Shall i raise a new issue?

Thanks again, a really useful extention!

**Comment by paulshestakov** [comment]
Yep, added parent -> child edges for `Catch` and `Retry` properties, you may update the extension now
It should be like this
Thank you for feedback!
![image](https://user-images.githubusercontent.com/9156851/104203146-ddbf3a00-543c-11eb-837d-58f53e58e1b2.png)
