### ISSUE TITLE
Error reporting on wrong format

### ISSUE THREAD

**Issue by Gloix** [PaulShestakov/aws-step-functions-constructor#3]
Currently the extension expects a structure with the following format:

    {"MyStepFunctions": 
      "definition": {
        "StartAt": "MyStartingState",
        "States": ...
    }}

but no error is given for a wrong structure, nor are direct structures supported (just the "StartAt" and "States" keys in the main dictionary).

**Comment by paulshestakov** [comment]
Direct structures should be supported now
Back then it was mainly focused on serverless format, but not anymore
